import { serve } from "https://deno.land/std@0.177.0/http/server.ts"
import { createClient } from "https://esm.sh/@supabase/supabase-js@2.39.3"

serve(async (req) => {
  // We can either call this manually or via pg_cron
  try {
    const supabaseAdmin = createClient(
      Deno.env.get('SUPABASE_URL') ?? '',
      Deno.env.get('SUPABASE_SERVICE_ROLE_KEY') ?? ''
    )

    // 1. Get the refresh token from sync_state
    const { data: stateData, error: stateError } = await supabaseAdmin
      .from('sync_state')
      .select('value')
      .eq('key', 'youtube_refresh_token')
      .single()

    if (stateError || !stateData?.value) {
      throw new Error("No YouTube refresh token found in database. Connect your account first.")
    }

    const refreshToken = stateData.value
    const clientId = Deno.env.get('GOOGLE_CLIENT_ID')
    const clientSecret = Deno.env.get('GOOGLE_CLIENT_SECRET')

    if (!clientId || !clientSecret) {
      throw new Error("Missing Google OAuth credentials in environment")
    }

    // 2. Get a fresh access token using the refresh token
    const tokenResponse = await fetch('https://oauth2.googleapis.com/token', {
      method: 'POST',
      headers: {
        'Content-Type': 'application/x-www-form-urlencoded',
      },
      body: new URLSearchParams({
        client_id: clientId,
        client_secret: clientSecret,
        refresh_token: refreshToken,
        grant_type: 'refresh_token',
      }),
    })

    const tokenData = await tokenResponse.json()
    if (!tokenResponse.ok) {
      throw new Error(`Failed to refresh token: ${tokenData.error_description || tokenData.error}`)
    }

    const accessToken = tokenData.access_token

    // 3. Generate the smart shuffle
    // Using 40 tracks for a monthly playlist
    const { data: playlistData, error: rpcError } = await supabaseAdmin.rpc('generate_smart_shuffle', { playlist_size: 40 })

    if (rpcError || !playlistData) {
      throw new Error("Failed to generate smart shuffle")
    }

    // 4. Filter to tracks that have valid youtube_video_id
    const tracks = playlistData as any[]
    const validTracks = tracks.filter((t) => t.youtube_video_id && t.youtube_video_id !== '__not_found__')

    if (validTracks.length === 0) {
      throw new Error("No valid YouTube tracks found in the generated playlist.")
    }

    // 5. Create a YouTube Playlist
    const monthYear = new Date().toLocaleString('en-IN', { month: 'long', year: 'numeric' })
    const createRes = await fetch('https://www.googleapis.com/youtube/v3/playlists?part=snippet,status', {
      method: 'POST',
      headers: { 
        Authorization: `Bearer ${accessToken}`, 
        'Content-Type': 'application/json' 
      },
      body: JSON.stringify({
        snippet: { 
          title: `YTMusic+ Discovery — ${monthYear}`, 
          description: `Automatically generated by YTMusic+ on ${new Date().toLocaleDateString('en-IN')}` 
        },
        status: { privacyStatus: 'private' },
      }),
    })
    
    const { id: playlistId } = await createRes.json()
    if (!playlistId) throw new Error('Failed to create YouTube playlist')

    // 6. Add tracks to the YouTube Playlist
    // We add them sequentially to preserve order and avoid rate limits.
    let addedCount = 0
    for (const track of validTracks) {
      const addRes = await fetch('https://www.googleapis.com/youtube/v3/playlistItems?part=snippet', {
        method: 'POST',
        headers: { 
          Authorization: `Bearer ${accessToken}`, 
          'Content-Type': 'application/json' 
        },
        body: JSON.stringify({
          snippet: { 
            playlistId, 
            resourceId: { kind: 'youtube#video', videoId: track.youtube_video_id } 
          },
        }),
      })

      if (addRes.ok) {
        addedCount++
      } else {
        const err = await addRes.json()
        console.warn(`Failed to add track ${track.youtube_video_id}:`, err)
      }
    }

    return new Response(
      JSON.stringify({
        message: "Monthly playlist generated successfully",
        playlistUrl: `https://music.youtube.com/playlist?list=${playlistId}`,
        totalAdded: addedCount
      }),
      { status: 200, headers: { 'Content-Type': 'application/json' } }
    )

  } catch (error: any) {
    console.error("Error generating monthly playlist:", error)
    return new Response(
      JSON.stringify({ error: error.message }),
      { status: 400, headers: { 'Content-Type': 'application/json' } }
    )
  }
})
